version: "1.0"

services:
  app:
    container_name: app-dev
    image: app-dev
    build: 
      target: development
    volumes:
      - ./src:/Frontend/src
    ports:
      - 3000:3000
